### ISSUE TITLE
Manager doesn't reload after setup

### ISSUE THREAD

**Issue by aditiapratama** [armadillica/flamenco-manager#4]
I've followed the instruction with manager setup, but after saving the conf, it won't connect back to manager. Here's my log 
```bash
./flamenco-manager -setup
WARN[2017-09-23T22:43:50+07:00] Flamenco Server URL: https://cloud.blender.org/ 
INFO[2017-09-23T22:43:50+07:00] Entering setup mode                          
INFO[2017-09-23T22:43:50+07:00] Point your browser at any of these URLs:     
INFO[2017-09-23T22:43:50+07:00]   - http://192.168.1.254:8083/setup          
INFO[2017-09-23T22:43:50+07:00]   - http://192.168.15.23:8083/setup          
INFO[2017-09-23T22:43:50+07:00]   - http://10.8.0.1:8083/setup               
INFO[2017-09-23T22:43:50+07:00]   - http://172.17.0.1:8083/setup             
INFO[2017-09-23T22:43:50+07:00]   - http://25.1.130.144:8083/setup           
INFO[2017-09-23T22:43:50+07:00]   - http://[2620:9b::1901:8290]:8083/setup   
INFO[2017-09-23T22:44:31+07:00] Merging configuration with POST data         
INFO[2017-09-23T22:44:31+07:00] Saved configuration file to flamenco-manager.yaml 
WARN[2017-09-23T22:44:48+07:00] Restarting Flamenco Manager by request of the web setup. 
INFO[2017-09-23T22:44:48+07:00] Signal 'interrupt' received, shutting down.  
INFO[2017-09-23T22:44:48+07:00] Shutting down HTTP server                    
WARN[2017-09-23T22:44:48+07:00] HTTP server: http: Server closed             
INFO[2017-09-23T22:44:48+07:00] Waiting for shutdown to complete.            
WARN[2017-09-23T22:44:48+07:00] Shutdown complete, stopping process.         
WARN[2017-09-23T22:44:48+07:00] Restarting Flamenco Server                   
INFO[2017-09-23T22:44:48+07:00] Started another Flamenco Manager /media/farm/flamenco/manager/flamenco-manager [-verbose] 
root@master:/media/farm/flamenco/manager# INFO[2017-09-23T22:44:48+07:00] Starting Flamenco Manager version 2.0.15     
WARN[2017-09-23T22:44:48+07:00] Flamenco Server URL: https://cloud.blender.org/ 
INFO[2017-09-23T22:44:48+07:00] MongoDB executable: /media/farm/flamenco/manager/mongodb-linux/bin/mongod 
INFO[2017-09-23T22:44:48+07:00] MongoDB database path: ./db                  
INFO[2017-09-23T22:44:48+07:00] MongoDB will be listening on port 27019      
INFO[2017-09-23T22:44:48+07:00] MongoDB is running at PID 24645              
INFO[2017-09-23T22:44:48+07:00] MongoDB database server : mongodb://localhost:27019/flamanager 
INFO[2017-09-23T22:44:48+07:00] Upstream Flamenco server: https://cloud.blender.org/ 
INFO[2017-09-23T22:44:48+07:00] Connecting to MongoDB at mongodb://localhost:27019/flamanager 
WARN[2017-09-23T22:44:48+07:00] MongoDB: 2017-09-23T22:44:48.828+0700 I CONTROL  [main] log file "/media/farm/flamenco/manager/mongodb-logs/mongodb.log" exists; moved to "/media/farm/flamenco/manager/mongodb-logs/mongodb.log.2017-09-23T15-44-48". 
PANI[2017-09-23T22:45:00+07:00] Unable to connect to MongoDB: no reachable servers 
panic: Unable to connect to MongoDB: no reachable servers [recovered]
	panic: (*logrus.Entry) (0x904aa0,0xc420184230)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc42007e2d0, 0xc4201761e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc400000000, ...)
	/go-local/src/github.com/sirupsen/logrus/entry.go:128 +0x615
github.com/sirupsen/logrus.(*Entry).Panic(0xc4201841e0, 0xc4201357b0, 0x1, 0x1)
	/go-local/src/github.com/sirupsen/logrus/entry.go:173 +0xaa
github.com/sirupsen/logrus.(*Logger).Panic(0xc42007e2d0, 0xc4201357b0, 0x1, 0x1)
	/go-local/src/github.com/sirupsen/logrus/logger.go:236 +0x6d
github.com/sirupsen/logrus.Panic(0xc4201357b0, 0x1, 0x1)
	/go-local/src/github.com/sirupsen/logrus/exported.go:107 +0x4b
main.main.func1()
	/go-local/src/flamenco-manager/main.go:353 +0x80
panic(0x869340, 0xc420174100)
	/usr/local/go/src/runtime/panic.go:491 +0x283
flamenco-manager/flamenco.MongoSession(0xb9aa40, 0x1c)
	/go-local/src/flamenco-manager/flamenco/db.go:30 +0x1ad
main.normalMode(0x0, 0x0, 0xc420010968)
	/go-local/src/flamenco-manager/main.go:263 +0x160
main.main()
	/go-local/src/flamenco-manager/main.go:373 +0x7c8

```

**Comment by sybrenstuvel** [comment]
Please attach your `/media/farm/flamenco/manager/mongodb-logs/mongodb.log` file from right after this happened. Also include info about which Flamenco Manager version you're using, and on which platform.

**Comment by aditiapratama** [comment]
@sybrenstuvel here's the log file 
[mongodb.log](https://github.com/armadillica/flamenco-manager-go/files/1338717/mongodb.log)

I'm using latest `2.0.15` on Ubuntu 16.04

**Comment by sybrenstuvel** [comment]
What kind of filesystem is `/media/farm/flamenco/manager/`? Is it a local ext4 partition? An NFS share? Something else? The error that MongoDB gives are similar to what happens when you try to [run MongoDB with a database on a VirtualBox Shared Folder](https://github.com/docker-library/mongo/issues/74).

**Comment by aditiapratama** [comment]
@sybrenstuvel it's samba cifs mounted at /etc/fstab

**Comment by sybrenstuvel** [comment]
Please mention such things in your first report, as it's not a tiny insignificant detail. Such a setup is apparently not supported by MongoDB. Have you tried running with the Mongo database files on a local filesystem?

**Comment by aditiapratama** [comment]
@sybrenstuvel ah sorry about that. i haven't use mongodb on local yet, but I have it installed tho. Any docs that pointing how to run manager with local installed mongodb?

Thanks before

**Comment by sybrenstuvel** [comment]
You don't need a locally installed MongoDB, just configure Flamenco Manager to use a local path. In other words, set `database_path` to something like `/opt/flamenco/db` instead of `./db`.

By the way, I took this opportunity to clarify the web setup and example config file as well (https://github.com/armadillica/flamenco-manager-go/commit/477f9c9839d739d5f37bf4da2fba72e0d0e6c8d6) ;-)

**Comment by aditiapratama** [comment]
@sybrenstuvel I've got the following error when setup MongoDB using absolute path in `/media/farm/flamenco/manager/db`

```bash
./flamenco-manager -setup
WARN[2017-10-01T20:03:04+07:00] Flamenco Server URL: https://cloud.blender.org/ 
INFO[2017-10-01T20:03:04+07:00] Entering setup mode                          
INFO[2017-10-01T20:03:04+07:00] Point your browser at any of these URLs:     
INFO[2017-10-01T20:03:04+07:00]   - http://192.168.1.254:8083/setup          
INFO[2017-10-01T20:03:04+07:00]   - http://192.168.15.23:8083/setup          
INFO[2017-10-01T20:03:04+07:00]   - http://10.8.0.1:8083/setup               
INFO[2017-10-01T20:03:04+07:00]   - http://25.1.130.144:8083/setup           
INFO[2017-10-01T20:03:04+07:00]   - http://[2620:9b::1901:8290]:8083/setup   
INFO[2017-10-01T20:03:04+07:00]   - http://172.17.0.1:8083/setup             
INFO[2017-10-01T20:03:27+07:00] Merging configuration with POST data         
INFO[2017-10-01T20:03:27+07:00] Saved configuration file to flamenco-manager.yaml 
WARN[2017-10-01T20:03:33+07:00] Restarting Flamenco Manager by request of the web setup. 
INFO[2017-10-01T20:03:33+07:00] Signal 'interrupt' received, shutting down.  
INFO[2017-10-01T20:03:33+07:00] Shutting down HTTP server                    
WARN[2017-10-01T20:03:33+07:00] HTTP server: http: Server closed             
INFO[2017-10-01T20:03:33+07:00] Waiting for shutdown to complete.            
WARN[2017-10-01T20:03:33+07:00] Shutdown complete, stopping process.         
WARN[2017-10-01T20:03:33+07:00] Restarting Flamenco Server                   
INFO[2017-10-01T20:03:33+07:00] Started another Flamenco Manager /media/farm/flamenco/manager/flamenco-manager [-verbose] 
root@master:/media/farm/flamenco/manager# INFO[2017-10-01T20:03:33+07:00] Starting Flamenco Manager version 2.0.15     
WARN[2017-10-01T20:03:33+07:00] Flamenco Server URL: https://cloud.blender.org/ 
INFO[2017-10-01T20:03:33+07:00] MongoDB executable: /media/farm/flamenco/manager/mongodb-linux/bin/mongod 
INFO[2017-10-01T20:03:33+07:00] MongoDB database path: /media/farm/flamenco/manager/db 
INFO[2017-10-01T20:03:33+07:00] MongoDB will be listening on port 27019      
INFO[2017-10-01T20:03:33+07:00] MongoDB is running at PID 9957               
INFO[2017-10-01T20:03:33+07:00] MongoDB database server : mongodb://localhost:27019/flamanager 
INFO[2017-10-01T20:03:33+07:00] Upstream Flamenco server: https://cloud.blender.org/ 
INFO[2017-10-01T20:03:33+07:00] Connecting to MongoDB at mongodb://localhost:27019/flamanager 
INFO[2017-10-01T20:03:33+07:00] My URL is               :http://192.168.1.254:8083/ 
INFO[2017-10-01T20:03:33+07:00] Listening at            ::8083               
INFO[2017-10-01T20:03:33+07:00] TaskUpdatePusher: Starting                   
WARN[2017-10-01T20:03:33+07:00] join group 0 operation not supported         
WARN[2017-10-01T20:03:33+07:00] join group 1 operation not supported         
WARN[2017-10-01T20:03:33+07:00] join group 2 operation not supported         
WARN[2017-10-01T20:03:33+07:00] join group 3 operation not supported         
WARN[2017-10-01T20:03:33+07:00] join group 4 operation not supported         
WARN[2017-10-01T20:03:33+07:00] join group 5 operation not supported         
FATA[2017-10-01T20:03:33+07:00] Error creating ssdp server: Unable to find a compatible network interface! 
```
Here's the mongodb.log as well.
[mongodb (2).log](https://github.com/armadillica/flamenco-manager-go/files/1347144/mongodb.2.log)

**Comment by sybrenstuvel** [comment]
I'll have to clarify the error message, that's for sure. This is about the UPnP/SSDP autodetection, which apparently doesn't want to start on your system. Can you give me the output of `ip a`, and some more information about your system's network cards?

**Comment by aditiapratama** [comment]
@sybrenstuvel here's the output of `ip a`

```bash
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:e0:4c:80:1a:50 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.254/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::2e0:4cff:fe80:1a50/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d0:27:88:7b:a2:dd brd ff:ff:ff:ff:ff:ff
    inet 192.168.15.23/24 brd 192.168.15.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::d227:88ff:fe7b:a2dd/64 scope link 
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none 
    inet 10.8.0.1 peer 10.8.0.2/32 scope global tun0
       valid_lft forever preferred_lft forever
5: ham0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1404 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 7a:79:19:01:82:90 brd ff:ff:ff:ff:ff:ff
    inet 25.1.130.144/8 brd 25.255.255.255 scope global ham0
       valid_lft forever preferred_lft forever
    inet6 2620:9b::1901:8290/96 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::7879:19ff:fe01:8290/64 scope link 
       valid_lft forever preferred_lft forever
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:c6:f1:b0:b3 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

And here's the output of `lspci | grep "Ethernet"`
```bash
lspci | grep "Ethernet"
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 02)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 02)
```

**Comment by sybrenstuvel** [comment]
Can you try with [this build](https://github.com/armadillica/flamenco-manager/files/1351900/flamenco-manager-2.0.16-dev-linux.tar.gz)?

For future reference, this was built from c0479ccec223b816d46f62df54638482fcd74032.

**Comment by sybrenstuvel** [comment]
Any progress here?

**Comment by sybrenstuvel** [comment]
Closing due to inactivity. Fee free to re-open with more information or concrete questions.
